package Formularios;

import PolimorfismoInterface.Entrenador;
import PolimorfismoInterface.Futbolista;
import PolimorfismoInterface.Masajista;
import PolimorfismoInterface.SeleccionFutbol;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Dalton
 */
public class frm_main extends javax.swing.JFrame {

    /**
     * Creates new form frm_main
     */
    public frm_main() {
        initComponents();
        jLabel7.setEnabled(false);
        jLabel8.setEnabled(false);
        jLabel9.setEnabled(false);
        jSpinField1.setEnabled(false);
        jTextField5.setEnabled(false);
        jTextField6.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Gestión de Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 13, -1, -1));

        jLabel2.setText("ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 37, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 101, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 55, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 101, -1));

        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 55, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 101, -1));

        jLabel5.setText("Edad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 37, -1));

        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField4KeyTyped(evt);
            }
        });
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 101, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Futbolista", "Entrenador", "Masajista" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 101, -1));

        jLabel6.setText("Tipo:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 37, -1));

        jButton1.setText("Ingresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 359, -1, -1));

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 359, -1, -1));

        jLabel7.setText("Dorsal:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 251, 130, -1));
        getContentPane().add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 49, -1));

        jLabel8.setText("Posición:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 288, 90, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 101, -1));

        jLabel9.setText(" ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 120, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 101, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Concentrarse", "Viajar", "Entrenar", "Jugar Partido" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 143, -1));

        jLabel10.setText("Acción:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 43, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id = Integer.parseInt(jTextField1.getText());
        String nomb = jTextField2.getText();
        String apel = jTextField3.getText();
        int edaa = Integer.parseInt(jTextField4.getText());
        int accion = jComboBox2.getSelectedIndex();
        if (jComboBox1.getSelectedIndex() == 1) {

            int dorsal = jSpinField1.getValue();
            String posicion = jTextField5.getText();

            Futbolista fut1 = new Futbolista(dorsal, posicion, id, nomb, apel, edaa);

            fut1.imprimir();

            if (accion == 1) {
                fut1.concentrarse();

            }
            if (accion == 2) {
                fut1.viajar();
            }
            if (accion == 3) {
                fut1.entrenar();
            }

            if (accion == 4) {
                fut1.jugarPartido();
            }

            if (accion == 5) {
                fut1.entrevista();
                JOptionPane.showMessageDialog(null, "El jugador dio una entrevista");
            }

        }
        if (jComboBox1.getSelectedIndex() == 2) {
            int id_fed = jSpinField1.getValue();

            Entrenador ent1 = new Entrenador(id_fed, id, nomb, apel, edaa);

            if (accion == 1) {
                ent1.concentrarse();
            }
            if (accion == 2) {
                ent1.viajar();
            }
            if (accion == 3) {
                ent1.entrenar();
            }

            if (accion == 4) {
                ent1.jugarPartido();
            }

            if (accion == 5) {
                ent1.planificarEntrenamiento();
                JOptionPane.showMessageDialog(null, "El entrenador está planificando el entrenamiento");
            }

            ent1.imprimir();
        }

        if (jComboBox1.getSelectedIndex() == 3) {
            int años_exp = jSpinField1.getValue();
            String titul = jTextField6.getText();
            Masajista mas1 = new Masajista(titul, años_exp, id, nomb, apel, edaa);

            if (accion == 1) {
                mas1.concentrarse();

            }
            if (accion == 2) {
                mas1.viajar();
            }
            if (accion == 3) {
                mas1.entrenar();
            }

            if (accion == 4) {
                mas1.jugarPartido();
            }

            if (accion == 5) {
                mas1.darMasaje();
                JOptionPane.showMessageDialog(null, "El masajista dio un masaje");
            }

            mas1.imprimir();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyTyped
        int key = evt.getKeyChar();

        boolean numero = key >= 48 && key <= 57;

        if (!(numero)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextField4KeyTyped

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if (jComboBox1.getSelectedIndex() == 1) {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[]{" ", "Concentrarse", "Viajar", "Entrenar", "Jugar Partido", "Entrevista"}));

            jLabel7.setText("Dorsal:");
            jLabel8.setText("Posición:");
            jLabel9.setText(" ");
            jTextField6.setVisible(false);
            jTextField5.setVisible(true);

            jLabel7.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jSpinField1.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);

        }

        if (jComboBox1.getSelectedIndex() == 2) {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[]{" ", "Concentrarse", "Viajar", "Entrenar", "Jugar Partido", "Planificar Entrenamiento"}));

            jLabel7.setText("ID Federación");
            jLabel8.setText(" ");
            jLabel9.setText(" ");
            jTextField6.setVisible(false);

            jLabel7.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jSpinField1.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);
            jTextField5.setVisible(false);
            jTextField6.setVisible(false);

        }

        if (jComboBox1.getSelectedIndex() == 3) {
            jComboBox2.setModel(new DefaultComboBoxModel<>(new String[]{" ", "Concentrarse", "Viajar", "Entrenar", "Jugar Partido", "Dar Masaje"}));

            jLabel7.setText("Años de experiencia:");
            jLabel8.setText("Titulación: ");
            jLabel9.setText(" ");
            jTextField5.setVisible(true);
            jTextField6.setVisible(false);

            jLabel7.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jSpinField1.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);

            jLabel7.setEnabled(true);
            jLabel8.setEnabled(true);
            jLabel9.setEnabled(true);
            jSpinField1.setEnabled(true);
            jTextField5.setEnabled(true);
            jTextField6.setEnabled(true);

        }

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.components.JSpinField jSpinField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
