package Formularios;

import Controlador.TLista_Compañia;
import Entidades.Asalariado;
import Entidades.Empleado;
import Entidades.EmpleadoComision;
import Entidades.EmpleadosAsalariadoComision;
import java.util.Date;

/**
 *
 * @author Dalton
 */
public class frmEditEmpleados extends javax.swing.JFrame {

    /**
     * Creates new form frmTrabajador
     */
    public String Funcion;

    public frmEditEmpleados(String fun) {
        this.Funcion = fun;
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Ingreso de Trabajadores");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel2.setText("Cedula:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel3.setText("Nombres:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel6.setText("Fecha:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, -1, -1));

        jLabel7.setText("Estado:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 160, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione una opción>", "Soltero", "Casado", "Viudo", "Divorciado" }));
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 170, -1));

        jLabel8.setText("Tipo:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione una opción>", "Asalariado", "Comision", "Asalariado Comision" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 170, -1));

        jLabel9.setText("Sueldo:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        jLabel10.setText("Bonificación:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 150, -1));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 150, -1));

        jButton2.setText("Ingresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        jLabel4.setText("Apellidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, -1));

        jLabel11.setText("Descuento:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, -1, -1));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 150, -1));

        jLabel12.setText("Mes:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione opción>", "Marzo", "Diciembre", "Otros" }));
        getContentPane().add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 160, -1));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 170, -1));

        jLabel5.setText("Codigo:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 160, -1));

        jLabel13.setText("Diezmo:");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 500, 150, -1));

        jLabel14.setText("Ciudad");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 150, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void SetDatos(Empleado op) {
        jTextField7.setText(op.getCodigo());
        jTextField1.setText(op.getCedula());
        jTextField2.setText(op.getNombre());
        jTextField3.setText(op.getApellido());

        jComboBox2.setSelectedItem(op.getEstado());
        jComboBox3.setSelectedItem(op.getTipo());
        jDateChooser1.setDate(op.getFechaNaci());
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        if (jComboBox3.getSelectedItem().toString().equals("Asalariado")) {
            jLabel9.setText("Sueldo:");
            jLabel10.setText("Bonificación:");
            jLabel11.setText("Descuento:");
            jLabel13.setText("Diezmo:");
            jTextField8.setEnabled(true);
            jLabel11.setEnabled(true);
            jTextField6.setEnabled(true);
            jTextField6.setEnabled(true);
            jLabel13.setEnabled(true);
        }
        if (jComboBox3.getSelectedItem().toString().equals("Comision")) {
            jLabel9.setText("Tarifa:");
            jLabel10.setText("Ventas:");
            jLabel11.setText("");
            jLabel13.setText("");
            jLabel11.setEnabled(false);
            jTextField6.setEnabled(false);
            jLabel13.setEnabled(false);
             jTextField8.setEnabled(false);
        }

        if (jComboBox3.getSelectedItem().toString().equals("Asalariado Comision")) {
            jLabel9.setText("Sueldo:");
            jLabel10.setText("Tarifa:");
            jLabel11.setText("Ventas:");
            jLabel13.setText("");
            jLabel11.setEnabled(true);
            jTextField6.setEnabled(true);
            jTextField6.setEnabled(true);
            jLabel13.setEnabled(false);
             jTextField8.setEnabled(false);
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    Asalariado oa = null;
    EmpleadoComision oc = null;
    EmpleadosAsalariadoComision oac = null;
    String tip = null;
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        double v1 = 0, v2 = 0, v3 =0,v4= 0;
        String cod = jTextField7.getText();
        String ced = jTextField1.getText();
        String nom = jTextField2.getText();
        String ape = jTextField3.getText();
        String ciu = jTextField9.getText();
        Date fechan = jDateChooser1.getDate();
        String est = jComboBox2.getSelectedItem().toString();
        String tip = jComboBox3.getSelectedItem().toString();
        int tipo = jComboBox3.getSelectedIndex();
        String mess = jComboBox4.getSelectedItem().toString();

        if (tipo==1) {

            v1 = Double.parseDouble(jTextField4.getText());
            v2 = Double.parseDouble(jTextField5.getText());
            v3 = Double.parseDouble(jTextField6.getText());
            v4=Double.parseDouble(jTextField8.getText());
            oa = new Asalariado(v1, v2, v4, v3, cod, ced, nom, ape, fechan, est, ciu, mess, tip);

            if (Funcion.equals("Insertar")) {
                TLista_Compañia.Insertar(oa);
            }

            if (Funcion.equals("Modificar")) {
                jLabel12.setEnabled(false);
                jTextField1.setEnabled(false);
                TLista_Compañia.Modificar(TLista_Compañia.Buscar(ced), oa);
            }

            frmAdminEmpleados.ListarEmpleados();
        }

        if (tipo==2) {

            v1 = Double.parseDouble(jTextField4.getText());
            v2 = Double.parseDouble(jTextField5.getText());
            oc = new EmpleadoComision(v1, v2, cod, ced, nom, ape, fechan, est, ciu, mess, tip);

            if (Funcion.equals("Insertar")) {
                TLista_Compañia.Insertar(oc);
            }

            if (Funcion.equals("Modificar")) {
                jLabel12.setEnabled(false);
                jTextField1.setEnabled(false);
                TLista_Compañia.Modificar(TLista_Compañia.Buscar(ced), oc);
            }

            frmAdminEmpleados.ListarEmpleados();
        }

        if (tipo==3) {

            v1 = Double.parseDouble(jTextField4.getText());
            v2 = Double.parseDouble(jTextField5.getText());
            oac = new EmpleadosAsalariadoComision(v1, v2, v3, cod, ced, nom, ape, fechan, est, ciu, mess, tip);

            if (Funcion.equals("Insertar")) {
                TLista_Compañia.Insertar(oac);
            }

            if (Funcion.equals("Modificar")) {
                jLabel12.setEnabled(false);
                jTextField1.setEnabled(false);
                TLista_Compañia.Modificar(TLista_Compañia.Buscar(ced), oac);
            }

            frmAdminEmpleados.ListarEmpleados();
        }
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEditEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEditEmpleados("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
