public class Busqueda_binaria_Frame extends javax.swing.JFrame {
 static int N;
    static int T;
    static int [] V;
    static int [] A;
    /**
     * Creates new form Busqueda_binaria_Frame
     */
    public Busqueda_binaria_Frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_aleatorio = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_ingresar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_mostrar = new javax.swing.JTextArea();
        txt_ordenado = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_numal = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Busqueda Binaria");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 40));
        getContentPane().add(txt_aleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 120, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, -1, 20));

        jLabel3.setText("Ingrese los datos del vector");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 160, 20));
        getContentPane().add(txt_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, -1));

        jLabel4.setText("Ingrese cuantos números aleatorios desea generar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 280, 20));

        txt_mostrar.setColumns(20);
        txt_mostrar.setRows(5);
        jScrollPane1.setViewportView(txt_mostrar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        getContentPane().add(txt_ordenado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 120, -1));

        jLabel5.setText("Números ordenados");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 120, -1));

        jLabel6.setText("Números aleatorios");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 120, 20));

        txt_numal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_numalActionPerformed(evt);
            }
        });
        getContentPane().add(txt_numal, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 120, -1));

        btn_buscar.setText("Start");
        btn_buscar.setActionCommand("buscar");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
         System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        ingreso();
        generar();
        ordenar();
        resultado();
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_numalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_numalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_numalActionPerformed
   public static int busqueda(int vector[], int dato){
        int n = vector.length;
        int centro,inf=0,sup=n-1;
        while(inf<=sup){
            centro=(sup+inf)/2;
            if(vector[centro]==dato) return centro;
            else if(dato < vector [centro] )sup=centro-1;
            else inf=centro+1;
        }
        return -1;
    }
    
    public void ingreso(){
       String ingreso = txt_ingresar.getText();
       String[] datos= ingreso.split(",");
       String vector1="";
       N=datos.length;
       V= new int [N];
       for(int i = 0; i<N ; i++){
            V[i] = Integer.parseInt(datos[i]);
            vector1 += (V[i] + ",");
        }
    
        txt_mostrar.setText("[ " + vector1 + " ]");
    }
    public static void generar(){
        T = Integer.parseInt(txt_numal.getText());
        A = new int [T];
        String vector3 = "";
        for (int i = 0 ; i< A.length; i++){
            int all = (int) (Math.random()*20);
            A[i] = all;
            vector3 += (A[i] + ",");
        }
        txt_aleatorio.setText("[ " + vector3 + " ]");
    }
     public static void ordenar(){
        for (int i = 0; i < N - 1; i++) {
            for (int j = 0; j < N - i - 1; j++) {
                if (V[j] > V[j + 1]) {
                    int temporal = V[j];
                    V[j] = V[j + 1];
                    V[j + 1] = temporal;
                }
            }
        }
         String vector2 = "";
        for (int i = 0; i < N; i++) {
            vector2 += (V[i] + ",");
        }
        txt_ordenado.setText("[ " + vector2 + " ]");
    }
     public static void resultado(){
        for (int k = 0; k<A.length; k++){
            int B = busqueda(V,A[k]);
            if (B==-1) txt_mostrar.append("\n " + A[k] + " No encontrado");
            else txt_mostrar.append("\n " + A[k] + " Encontrado en la posicion " +(B));
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Busqueda_binaria_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Busqueda_binaria_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Busqueda_binaria_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Busqueda_binaria_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Busqueda_binaria_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btn_buscar;
    public static javax.swing.JButton btn_salir;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField txt_aleatorio;
    public static javax.swing.JTextField txt_ingresar;
    public static javax.swing.JTextArea txt_mostrar;
    public static javax.swing.JTextField txt_numal;
    public static javax.swing.JTextField txt_ordenado;
    // End of variables declaration//GEN-END:variables
}
