package Formularios;

import Controladores.TlistaEquipo;
import Entidades.Entrenador;
import Entidades.Futbolista;
import Entidades.Masajista;
import Entidades.SeleccionFutbol;
import java.util.Date;

/**
 *
 * @author Dalton
 */
public class frmInsertar extends javax.swing.JFrame {

    /**
     * Creates new form frmInsertar
     */
    public String Funcion;
    public String Clase;

    public frmInsertar(String fun, String clase) {
        initComponents();
        jLabel1.setText("INGRESAR DATOS: " + clase.toUpperCase());
        this.Funcion = fun;
        this.Clase = clase;
        jTextField1.setEditable(false);
        jTextField1.setText(String.valueOf((TlistaEquipo.ListaSeleccion.size() + 1)));
        setLocationRelativeTo(this);
        setMenu();
    }

    public void setDatos(SeleccionFutbol pe) {

        jTextField1.setText(String.valueOf(pe.getId()));
        jTextField2.setText(pe.getNombre());
        jTextField3.setText(pe.getApellidos());
        jSpinField1.setValue(pe.getEdad());

        if (Clase.equals("Futbolista")) {
            jTextField4.setText(((Futbolista) pe).getDemarcacion());
            jSpinField2.setValue(((Futbolista) pe).getDorsal());
        }
        if (Clase.equals("Entrenador")) {
            jSpinField2.setValue(((Entrenador) pe).getIdFederacion());
        }
        if (Clase.equals("Masajista")) {
            jSpinField2.setValue(((Masajista) pe).getAniosExperiencia());
            jTextField4.setText(((Masajista) pe).getTitulacion());
        }
    }

    public void setMenu() {
        if (Clase.equals("Futbolista")) {
            jLabel5.setText("Dorsal:");
            jLabel6.setText("Posicion de juego: ");
        }
        if (Clase.equals("Entrenador")) {
            jLabel5.setText("ID Federacion:");
            jLabel6.setText("");
            jTextField4.setVisible(false);
        }
        if (Clase.equals("Masajista")) {
            jLabel5.setText("Años experiencia:");
            jLabel6.setText("Titulacion:");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSpinField1 = new com.toedter.components.JSpinField();
        jSpinField2 = new com.toedter.components.JSpinField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ingreso de Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 360, -1));

        jLabel2.setText("Edad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Apellido:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel8.setText("Id:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 190, -1));
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 190, -1));
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 190, -1));

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 80, -1));
        getContentPane().add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 50, -1));
        getContentPane().add(jSpinField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 50, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public boolean Validar() {
        if (jTextField1.getText().equals("") && jTextField2.getText().equals("") && jTextField3.getText().equals("") && jTextField4.equals("")) {
            return false;
        }
        return true;
    }

    public void Limpiar() {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jSpinField1.setValue(0);
        jSpinField2.setValue(0);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (Validar()) {
            int id = Integer.valueOf(jTextField1.getText());
            String nom = jTextField2.getText();
            String ape = jTextField3.getText();
            int edad = jSpinField1.getValue();

            SeleccionFutbol sf = null;

            if (Clase.equals("Futbolista")) {
                sf = new Futbolista(id, nom, ape, edad, jSpinField2.getValue(), jTextField4.getText());
            }
            if (Clase.equals("Entrenador")) {
                sf = new Entrenador(id, nom, ape, edad, jSpinField2.getValue());
            }
            if (Clase.equals("Masajista")) {
                sf = new Masajista(id, nom, ape, edad, jTextField4.getText(), jSpinField2.getValue());
            }
            if (Funcion.equals("Insertar")) {
                TlistaEquipo.Insert(sf);
            }
            if (Funcion.equals("Modificar")) {
                TlistaEquipo.Edit(sf, TlistaEquipo.Buscar(id));
            }

            this.hide();
            Limpiar();
            try {
                frmTabla.listarTabla(Clase);
            } catch (NullPointerException ex) {

            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInsertar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInsertar("", "").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
