package Formularios;

import Controlador.TL_Venta_Boletos;
import Controlador.TL_Mesas_Mozos;
import Entidades.LO_Venta_Boletos;
import javax.swing.JOptionPane;

/**
 *
 * @author Dalton
 */
public class frm_edit_LO_Venta_Boletos extends javax.swing.JFrame {

    /**
     * Creates new form frm_Venta_Boletos
     */
    
    public String Funcion;

    public frm_edit_LO_Venta_Boletos(String fun) {
        this.Funcion = fun;
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmb_compañia = new javax.swing.JComboBox<>();
        cmb_destino = new javax.swing.JComboBox<>();
        cmb_servicio = new javax.swing.JComboBox<>();
        txt_cantidad_boletos = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Venta de Boletos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 166, -1));

        jLabel2.setText("Compañia:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel3.setText("Destino:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel4.setText("Cantidad de boletos:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel5.setText("Tipo de Servicio:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        cmb_compañia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rutas Orenses", "Cifa", "Calderon" }));
        getContentPane().add(cmb_compañia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 140, -1));

        cmb_destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Quito", "Cuenca", "Guayaquil" }));
        getContentPane().add(cmb_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));

        cmb_servicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Común", "Diferencial" }));
        getContentPane().add(cmb_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 140, -1));
        getContentPane().add(txt_cantidad_boletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 140, -1));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        jButton3.setText("Guardar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 20));

        jLabel6.setText("ID Venta:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        if (cmb_compañia.getSelectedIndex() > 0 && cmb_destino.getSelectedIndex() > 0 && !txt_cantidad_boletos.getText().equals(" ") && cmb_servicio.getSelectedIndex() > 0) {

            String id = jTextField1.getText();
            String compa = cmb_compañia.getSelectedItem().toString();
            String desti = cmb_destino.getSelectedItem().toString();
            int cant = Integer.parseInt(txt_cantidad_boletos.getText());
            String servi = cmb_servicio.getSelectedItem().toString();

            LO_Venta_Boletos ovb = new LO_Venta_Boletos(id, compa, desti, cant, servi);

            if (Funcion.equals("Insertar")) {
                TL_Venta_Boletos.Insertar(ovb);
            }

            if (Funcion.equals("Modificar")) {
                
                id = jTextField1.getText();
                compa = cmb_compañia.getSelectedItem().toString();
                desti = cmb_destino.getSelectedItem().toString();
                cant = Integer.parseInt(txt_cantidad_boletos.getText());
                servi = cmb_servicio.getSelectedItem().toString();
                
                jTextField1.setEnabled(false);
                TL_Venta_Boletos.Modificar(TL_Venta_Boletos.Buscar(id), ovb);
            }

            frm_Admin_LO_Venta_Boletos.Listar();
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Ingrese correctamente los datos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_edit_LO_Venta_Boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_edit_LO_Venta_Boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_edit_LO_Venta_Boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_edit_LO_Venta_Boletos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_edit_LO_Venta_Boletos("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_compañia;
    private javax.swing.JComboBox<String> cmb_destino;
    private javax.swing.JComboBox<String> cmb_servicio;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_cantidad_boletos;
    // End of variables declaration//GEN-END:variables
}
