package Taller3_2;

/**
 *
 * @author Dalton
 */
public class ciudades extends javax.swing.JFrame {
        static int MAX=30;
	static int N=0;static 
                String[] V = new String[MAX]; 
    /**
     * Creates new form ciudades
     */
    public ciudades() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        txt_ingreso = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btn_busquedad_s = new javax.swing.JButton();
        txt_busqueda = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btn_limpiar = new javax.swing.JButton();
        txt_modificar = new javax.swing.JTextField();
        btn_eliminar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_ordenar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_ingresar = new javax.swing.JButton();
        caja_1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_mostrar = new javax.swing.JTextArea();
        btn_busqueda_p = new javax.swing.JButton();
        btn_Mostrar1 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Gestor de Datos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 170, -1));
        jLabel1.getAccessibleContext().setAccessibleName("");

        getContentPane().add(txt_ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, -1));

        jLabel2.setText("Ingrese una ciudad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 120, -1));

        jLabel3.setText("Buscar una ciudad");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 110, -1));

        btn_busquedad_s.setText("Busqueda S");
        btn_busquedad_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busquedad_sActionPerformed(evt);
            }
        });
        getContentPane().add(btn_busquedad_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 100, -1, -1));
        getContentPane().add(txt_busqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, -1));

        jLabel4.setText("Eliminar y Actualizar");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        btn_limpiar.setText("Limpiar");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 100, 30));
        getContentPane().add(txt_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 130, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, -1, -1));

        btn_actualizar.setText("Actualizar");
        btn_actualizar.setToolTipText("");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        btn_ordenar.setText("Ordenar");
        btn_ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ordenarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ordenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 100, 30));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 100, 30));

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));

        getContentPane().add(caja_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 110, -1));

        jLabel5.setText("Ciudades");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txt_mostrar.setColumns(20);
        txt_mostrar.setRows(5);
        jScrollPane2.setViewportView(txt_mostrar);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 250, 100));

        btn_busqueda_p.setText("Busqueda P");
        btn_busqueda_p.setActionCommand("");
        btn_busqueda_p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_busqueda_pActionPerformed(evt);
            }
        });
        getContentPane().add(btn_busqueda_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        btn_Mostrar1.setText("Mostrar");
        btn_Mostrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Mostrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Mostrar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 100, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        ingresar();
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_ordenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ordenarActionPerformed
        ordenar();
        mostrar();
    }//GEN-LAST:event_btn_ordenarActionPerformed

    private void btn_busquedad_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busquedad_sActionPerformed
    txt_mostrar.setText("");
        String dato = txt_busqueda.getText();
        int pos= busquedaSecuencial(dato);
        if(pos>=0)
        txt_mostrar.append("\n La Ciudad "+dato+" está registrada en la posición " + (pos+1) );
        else txt_mostrar.append("\n Ciudad no registrada");
        txt_busqueda.setText("");
    
    }//GEN-LAST:event_btn_busquedad_sActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
    System.exit(0);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        actualizar();
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_busqueda_pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_busqueda_pActionPerformed
        txt_mostrar.setText("");
        String dato = txt_busqueda.getText();
        txt_mostrar.append("Ciudades encontradas con: " + dato+"\n" );
        busquedaParcial(dato);
    }//GEN-LAST:event_btn_busqueda_pActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void btn_Mostrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Mostrar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_Mostrar1ActionPerformed

    public static int busquedaSecuencial(String dato){
        for(int i=0; i<N; i++){
            if(dato.equalsIgnoreCase(V[i])){
                return i;
            }
        }
        return -1;
    }
    public void busquedaParcial(String cri){
        for(int i=0; i<N; i++){
            if (V[i].toLowerCase().contains(cri.toLowerCase()))
                txt_mostrar.append(V[i]+"\n ");
        }
    }
    public static void ingresar(){
        String cad= txt_ingreso.getText();
        String[] vectorcad =cad.split(",");
         N = vectorcad.length;
        for(int i = 0; i<N ; i++){
            V[i] = vectorcad[i];
            caja_1.addItem(V[i]);
        }
        //CB_ListaC.addItem(ciudades);
        txt_ingreso.setText("");
    }
    public void mostrar(){
        for(int i=0; i<N; i++){
            txt_mostrar.append(V[i]+"\n");
	}
    }
   public static void eliminar(){
        String dato = caja_1.getSelectedItem().toString();
        int E = caja_1.getSelectedIndex();
        caja_1.removeItemAt(E);
        int x = busquedaSecuencial(dato);
        for (int i = x; i < N; i++) {
            V[i]=V[i+1];
        }
        N--;
    }
   public static void actualizar(){
        String dato = caja_1.getSelectedItem().toString();
        int x = busquedaSecuencial(dato);
        if(x>=0){
            String actual = txt_modificar.getText();
            V[x]=actual;
        }
        caja_1.removeAllItems();
        for(int i = 0; i<N ; i++){
            caja_1.addItem(V[i]);
        }
    }
   public  void limpiar(){
   txt_mostrar.setText("");
   txt_ingreso.setText("");
   txt_busqueda.setText("");
   txt_modificar.setText("");
   }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ciudades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ciudades().setVisible(true);
            }
        });
    }
    public void ordenar(){
    for(int i=0; i<N-1; i++){
			for(int j=i+1;j<N;j++){
				if(V[j].compareToIgnoreCase(V[i])<0){
					String aux=V[i];
					V[i]=V[j];
					V[j]=aux;
                                        
                                        
				}
			}
		}
	caja_1.removeAllItems();
        for(int i = 0; i<N ; i++){
            caja_1.addItem(V[i]);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Mostrar1;
    private javax.swing.JButton btn_actualizar;
    public static javax.swing.JButton btn_busqueda_p;
    public static javax.swing.JButton btn_busquedad_s;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JButton btn_limpiar;
    public static javax.swing.JButton btn_ordenar;
    private javax.swing.JButton btn_salir;
    public static javax.swing.JComboBox<String> caja_1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    public static javax.swing.JTextField txt_busqueda;
    public static javax.swing.JTextField txt_ingreso;
    public static javax.swing.JTextField txt_modificar;
    private javax.swing.JTextArea txt_mostrar;
    // End of variables declaration//GEN-END:variables
}